# Generated by Django 5.1.6 on 2025-02-10 04:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the travel event (e.g., Weekly Travel)",
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the travel event")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the travel",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the vehicle", max_length=100, unique=True
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of passengers the vehicle can hold"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the user registering for the travel",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email for registration",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Unique username (optional)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "church_name",
                    models.CharField(
                        default="Mangabeira",
                        help_text="Name of the user's church",
                        max_length=100,
                    ),
                ),
                (
                    "has_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has paid for the travel or not",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_user_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions",
                        to="auth.permission",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        help_text="Travel event the user is registering for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.travel",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehicle selected by the user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "indexes": [
                    models.Index(fields=["email"], name="api_user_email_a7eefd_idx"),
                    models.Index(fields=["travel"], name="api_user_travel__cb3f04_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "travel"), name="unique_email_per_travel"
                    )
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
