# Generated by Django 5.1.5 on 2025-02-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the travel event (e.g., Weekly Travel)",
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the travel event")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the travel",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the vehicle", max_length=100, unique=True
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of passengers the vehicle can hold"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        help_text="Name of the user registering for the travel",
                        max_length=100,
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        help_text="Name of the user's school", max_length=100
                    ),
                ),
                (
                    "has_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has paid for the travel",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        help_text="Travel event the user is registering for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.travel",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehicle selected by the user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.vehicle",
                    ),
                ),
            ],
        ),
    ]
