# Generated by Django 5.1.5 on 2025-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregistration",
            name="school_name",
        ),
        migrations.AddField(
            model_name="userregistration",
            name="church_name",
            field=models.CharField(
                default="mangabeira",
                help_text="Name of the user's church",
                max_length=100,
            ),
        ),
    ]
