# Generated by Django 5.1.6 on 2025-02-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_userregistration_school_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregistration",
            old_name="user_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="userregistration",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="password",
            field=models.CharField(default="password", max_length=128),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="church_name",
            field=models.CharField(
                default="Mangabeira",
                help_text="Name of the user's church",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="has_paid",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has paid for the travel or not",
            ),
        ),
    ]
