services:
  db:
    container_name: maanaim-planner-db
    image: postgresql:16.6
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgrespassword
      PG_DB: maanaim
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', '${PG_DB}']
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - maanaim_network
networks:
  maanaim_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
