services:
  db:
    container_name: maanaim-planner-db
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: maanaim
    volumes:
      - maanaim_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'maanaim']
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - maanaim_network
networks:
  maanaim_network:
    driver: bridge
volumes:
  maanaim_data:
    name: maanaim-data
    driver: local
