import type { Metadata } from 'next'

import Navbar from '@/sections/Navbar'
import Footer from '@/sections/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='vsc-initialized'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
